### ISSUE TITLE
Request VersionSufix can be null or empty

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/FlubuCore#256] opened 2019-12-30 14:39 UTC
Hello @mzorec ,

When I tried to release the official version of the Nuget package, I encountered an error. I think this is caused by the VersionSufix being empty, so is this expected of the design?

If the design is this, is there a better way to avoid writing the ` if(VersionSufix!=nullorempty) ` condition?

```
target.AddCoreTask(x => x.Pack()
                        .NoBuild()
                        .Project(projectFile)
                        .IncludeSymbols()
                        .VersionSufix(/*here can not be null or empty*/)
                        .OutputDirectory(ArtifactsDir));
```

```
ERROR: Argument --version-suffix requires value. Task: DotnetPackTask
```

**Comment by mzorec** [comment] 2019-12-30 23:24
Hello @yang-xiaodong , Thank you for the sugesstion.

While this is by design that Flubu throws exception when executing external commands and value is not passed to the option that requires value. I agree with you that in this scenario it is more convinient that Flubu would just ignore VersionSuffix option if it is null or empty.

So I'll make an exception in this scenario. I've already commited the change and it will be available in the next version which will be released shortly. 

About your question  if you have similar problem somewhere else

> If the design is this, is there a better way to avoid writing the if(VersionSufix!=nullorempty) condition?

 If we take your previous scenario Instead of if statement you could write

```c#
target.AddCoreTask(x => x.Pack()
                        .NoBuild()
                        .Project(projectFile)
                        .IncludeSymbols()
                        .When(() => !string.IsNullOrEmpty(suffix), t => t.VersionSuffix(suffix)
                        .OutputDirectory(ArtifactsDir));
```

**Closed by mzorec** 2019-12-30 23:24 UTC
Labels: Proposal, enhancement
